"""
Django settings for cihat_dev project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import ipaddress
from pathlib import Path

import environ
from django.utils.csp import CSP
from environ.fileaware_mapping import FileAwareMapping


class StripEnv(environ.Env):
    def get_value(
        self, var, cast=None, default=environ.Env.NOTSET, parse_default=False
    ):
        val = super().get_value(
            var, cast=cast, default=default, parse_default=parse_default
        )
        if isinstance(val, str):
            return val.strip("\n")
        return val


env = StripEnv()
env.ENVIRON = FileAwareMapping()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", False)

ALLOWED_HOSTS = ["*"] if DEBUG else env.list("DJANGO_ALLOWED_HOSTS", default=[])

ADMIN_ADDRESS = env.str("ADMIN_ADDRESS", "admin/")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # third party
    "django_cleanup.apps.CleanupConfig",
    "django_extensions",
    # my apps
    "base.apps.BaseConfig",
    # site map
    "django.contrib.sites",
    "django.contrib.sitemaps",
]

SITE_ID = 1

MIDDLEWARE = [
    "base.middlewares.TrustedProxyMiddleware",
    "base.utils.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cihat_dev.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csp",
            ],
        },
    },
]

WSGI_APPLICATION = "cihat_dev.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static/",
]
STATIC_ROOT = BASE_DIR / "staticfiles/"


MEDIA_URL = "media/"


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "base.User"

# Email backend and settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env.str("EMAIL_HOST", "")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
USE_PGBOUNCER = env.bool("USE_PGBOUNCER", False)
DB_KEEPALIVES_IDLE = env.int("DB_KEEPALIVES_IDLE", 60)
DB_KEEPALIVES_INTERVAL = env.int("DB_KEEPALIVES_INTERVAL", 10)
DB_KEEPALIVES_COUNT = env.int("DB_KEEPALIVES_COUNT", 3)


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB_CIHAT", ""),
        "USER": env.str("POSTGRES_USER", ""),
        "PASSWORD": env.str("POSTGRES_PASSWORD", ""),
        "HOST": env.str("DB_HOST", "pgbouncer"),
        "PORT": env.str("POSTGRES_PORT", "6432" if USE_PGBOUNCER else "5432"),
        "CONN_MAX_AGE": env.int("DJANGO_DB_CONN_MAX_AGE", 0 if USE_PGBOUNCER else 60),
        "CONN_HEALTH_CHECKS": True,
        "DISABLE_SERVER_SIDE_CURSORS": USE_PGBOUNCER,
        "OPTIONS": {
            "keepalives": 1,
            "keepalives_idle": DB_KEEPALIVES_IDLE,
            "keepalives_interval": DB_KEEPALIVES_INTERVAL,
            "keepalives_count": DB_KEEPALIVES_COUNT,
            "connect_timeout": 10,
        },
    }
}
USE_S3 = (not DEBUG) and bool(env.str("CIHAT_BUCKET_NAME", ""))

if USE_S3:
    AWS_S3_CUSTOM_DOMAIN = env.str("AWS_S3_CUSTOM_DOMAIN", "static.cihatertem.dev")
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": "media",
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            },
        },
        "staticfiles": {
            "BACKEND": "base.storages.CustomS3ManifestStaticStorage",
            "OPTIONS": {
                "location": "static",
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
                "object_parameters": {
                    "CacheControl": "max-age=31536000, public",
                },
            },
        },
    }

    AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = env.str("CIHAT_BUCKET_NAME", "")
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_REGION_NAME = env.str("AWS_S3_REGION_NAME", "")
    if endpoint_url := env.str("AWS_S3_ENDPOINT_URL", ""):
        AWS_S3_ENDPOINT_URL = endpoint_url
    MEDIA_ROOT = None
else:
    MEDIA_ROOT = BASE_DIR / "media/"

# gunicorn 2+ workers ratelimit issue
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "ratelimit_cache",
    }
}

RATELIMIT_USE_CACHE = "default"
CONTACT_RATE_LIMIT = env.str("CONTACT_RATE_LIMIT", "2/m")

if not DEBUG:
    _raw = env.str("TRUSTED_PROXY_NETS", "")
    TRUSTED_PROXY_NETS = []

    USE_TRAEFIK_SECURITY_HEADERS = env.bool("DJANGO_USE_TRAEFIK_SECURITY_HEADERS", True)

    if _raw:
        for net in _raw.split(","):
            TRUSTED_PROXY_NETS.append(ipaddress.ip_network(net.strip()))

    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = env.str("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS
    ]  # e.g. ["https://example.com"]
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = env.str("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

    if USE_TRAEFIK_SECURITY_HEADERS:
        SECURE_HSTS_SECONDS = 0
        SECURE_HSTS_INCLUDE_SUBDOMAINS = False
        SECURE_HSTS_PRELOAD = False
    else:
        SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", 31536000)
        SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
            "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", True
        )
        SECURE_HSTS_PRELOAD = env.bool("DJANGO_SECURE_HSTS_PRELOAD", True)
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [
        CSP.SELF,
        "https://static.cihatertem.dev",
        CSP.NONCE,
        # CSP.STRICT_DYNAMIC, # Can be enabled if all scripts are loaded with nonces
    ],
    "object-src": [CSP.NONE],
    "style-src": [
        CSP.SELF,
        "https://static.cihatertem.dev",
        "https://fonts.cihatertem.dev",
        CSP.NONCE,
    ],
    "img-src": [
        CSP.SELF,
        "https://static.cihatertem.dev",
        "data:",
    ],
    "media-src": [CSP.SELF, "https://static.cihatertem.dev"],
    "frame-src": [CSP.SELF],
    "font-src": [
        CSP.SELF,
        "https://static.cihatertem.dev",
        "https://fonts.gstatic.com",
        "data:",
    ],
    "connect-src": [CSP.SELF, "https://static.cihatertem.dev"],
    "frame-ancestors": [CSP.SELF],
}
