# Generated by Django 4.0.3 on 2022-07-19 10:27

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=blog.models.post_directory_path, verbose_name="Post's Hero Image")),
                ('youtube_link', models.URLField(max_length=2000)),
                ('ingredients', models.TextField(help_text="Seperate tags with ','")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
