# Generated by Django 4.0.3 on 2022-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
