# Generated by Django 4.0.3 on 2022-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
