# Generated by Django 4.0.3 on 2022-07-19 12:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_remove_post_slug_post_title_slug'),
    ]

    operations = [
        migrations.AlterField(
                model_name='post',
                name='title_slug',
                field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
