# Generated by Django 4.0.3 on 2022-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_title_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=200, null=True, unique=True),
        ),
    ]
