# Generated by Django 4.0.3 on 2022-07-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_category_options_alter_post_difficulty_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
