# Generated by Django 4.0.3 on 2022-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(help_text="Seperate ingredients with ','"),
        ),
    ]
