# Generated by Django 4.0.3 on 2022-07-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, help_text="Seperate ingredients with ','", null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
