# Generated by Django 4.0.3 on 2022-09-14 09:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.post_directory_path, verbose_name="Post's Hero Image"),
        ),
    ]
