# Generated by Django 4.0.3 on 2022-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='snapshot',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name="Work's Landing Page Screenshot"),
        ),
    ]
