# Generated by Django 4.0.3 on 2022-03-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_works_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='snapshot_alt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Landing Page Screenshot Alt'),
        ),
    ]
