# Generated by Django 4.0.3 on 2022-03-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_works_snapshot_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.URLField(blank=True, max_length=2000, null=True, verbose_name="Work's URL")),
                ('work_title', models.CharField(blank=True, max_length=200, null=True)),
                ('snapshot', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name="Work's Landing Page Screenshot")),
                ('snapshot_alt', models.CharField(blank=True, max_length=200, null=True, verbose_name='Landing Page Screenshot Alt')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
