# Generated by Django 4.0.3 on 2022-03-03 08:35

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_work_rename_skills_skill_delete_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='snapshot',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=base.utils.work_directory_path, verbose_name="Work's Landing Page Screenshot"),
        ),
    ]
