# Generated by ChatGPT on 2025-09-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_spamfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamFilter',
        ),
    ]
